added navbar to position.html
rutaben/TYPE2_HTML-CSS-PROJECT-TEMPLATE pull request #1
Opened 2021-09-09 12:18 UTC by WildPigeon

2021-09-09 12:45 UTC, rutaben approved these changes

2021-09-10 05:45 UTC, ZilvinasVidmantas requested changes

2021-09-10 05:45 UTC, ZilvinasVidmantas commented on pages/position.html
> +</html>
missing end of file

2021-09-10 05:52 UTC, ZilvinasVidmantas approved these changes
Good Job, pigeon. Go Wild

2021-09-10 05:54 UTC, merged